package personaApp;

/**
* personaApp/personaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from persona.idl
* lunes 23 de abril de 2018 07:52:12 PM COT
*/

public final class personaHolder implements org.omg.CORBA.portable.Streamable
{
  public personaApp.persona value = null;

  public personaHolder ()
  {
  }

  public personaHolder (personaApp.persona initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = personaApp.personaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    personaApp.personaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return personaApp.personaHelper.type ();
  }

}
