package personaApp;


/**
* personaApp/personaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from persona.idl
* lunes 23 de abril de 2018 07:52:12 PM COT
*/

abstract public class personaHelper
{
  private static String  _id = "IDL:personaApp/persona:1.0";

  public static void insert (org.omg.CORBA.Any a, personaApp.persona that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static personaApp.persona extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (personaApp.personaHelper.id (), "persona");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static personaApp.persona read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_personaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, personaApp.persona value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static personaApp.persona narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof personaApp.persona)
      return (personaApp.persona)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      personaApp._personaStub stub = new personaApp._personaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static personaApp.persona unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof personaApp.persona)
      return (personaApp.persona)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      personaApp._personaStub stub = new personaApp._personaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
