package personaApp;


/**
* personaApp/personaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from persona.idl
* lunes 23 de abril de 2018 07:52:12 PM COT
*/

public interface personaOperations 
{
  boolean insertarPersona (int identifigacion, String nombre, String apellidos, int telefono, String direccion);
  String consultarPersona (int identificacion);
  boolean eliminarPersona (int identificacion);
  boolean actualizarPersona (int identifigacion, String nombre, String apellidos, int telefono, String direccion);
  String listarPersonas ();
  void shutdown ();
} // interface personaOperations
